global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'payment-gateway'
    static_configs:
      - targets: ['payment-gateway:5000']
    metrics_path: '/metrics'

  - job_name: 'tester'
    static_configs:
      - targets: ['tester:9090']
    metrics_path: '/metrics'
